version: "3.8"

services:
  web:
    container_name: django_pg_docker
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app

  db:
    image: postgres:13.0-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
